### ISSUE TITLE
http protocol on registry output is invalid

### ISSUE THREAD

**Issue by kevzettler** [elgohr/ecr-login-action#12]
The registry output returns a url with http protocol prepended like `https://809698098.dkr.ecr.us-east-1.amazonaws.com` If you pass this manually to `docker build` it will fail:

```
invalid argument "https://809698098.dkr.ecr.us-east-1.amazonaws.com/crashgiants:edb1219c31a7e2a27c56dc4b0f747ba191c781a7" for "-t, --tag" flag: invalid reference format
```

you need to then manually strip the `https://` it will pass.

`Docker version 19.03.13, build 4484c46d9d`

**Comment by elgohr** [comment]
Hey, thanks for bringing that up. Could you please check out https://github.com/elgohr/ecr-login-action/releases/tag/1.0.1 ?

**Comment by andre-lx** [comment]
Hi @elgohr this is not solved. We test it with the 1.0.1 release.

**Comment by elgohr** [comment]
Same error? It's hard for me to reproduce, as I don't have an account...
