### ISSUE TITLE
Branch master updated to main breaks our CI-CD

### ISSUE THREAD

**Issue by drnachio** [elgohr/ecr-login-action#14]
I fully respect the name change and understand that we must free ourselves from a nomenclature associated with the era of slavery, but in this case the effect of the change has been quite large.

This update has broken hundreds of CI-CD pipelines because the examples and documentation indicated that we should target the `master` branch.

```yaml
uses: elgohr/ecr-login-action@master
```

Can you please keep a master branch to maintain backwards compatibility?

**Comment by elgohr** [comment]
Sorry for the inconvenience. Pushed the master again.
I will update the README and mark it as deprecated, so that people can change

**Comment by elgohr** [comment]
Alright. I guess with a look at the numbers I'll keep the master branch and avoid further trouble for people depending on this. Will stick with master.

**Comment by elgohr** [comment]
Again, big sorry to everybody!
