### ISSUE TITLE
Add support for AWS_PROFILE

### ISSUE THREAD

**Issue by ismail44** [elgohr/ecr-login-action#18]
In some scenarios we use a builder role in some of our org accounts that is assumable by a central "builder user". It would be nice if this could use AWS_PROFILE (setup by "aws-actions/configure-aws-credentials@v1") in addition to the keys.

**Comment by elgohr** [comment]
So you’re running an Actions Runner inside AWS or how do you assume the role?

**Comment by ismail44** [comment]
Never mind... sometimes I don't read well enough :)
