### ISSUE TITLE
Ability to "not mask" Password

### ISSUE THREAD

**Issue by ismail44** [elgohr/ecr-login-action#19]
We have a use case where we need to use an image from a private ecr repo for a service, however, we need to generate an ECR Password before we can use the image. This isn't like a normal workflow where we could just through this action before an docker pull (or push), since we are using the image in a service.

We tried to run this as a setup and output the password, however, because "set-mask" is set for the password, GithubActions will not output the password.

**Comment by elgohr** [comment]
According to the GitHub marketplace terms of service (https://docs.github.com/en/site-policy/github-terms/github-marketplace-developer-agreement#3restrictions-and-responsibilities) I would be in charge regarding lost tokens. I'm not taking this risk.
