### ISSUE TITLE
Must provide --username with --password-stdin Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by sameeraksc** [elgohr/ecr-login-action#20]
Hello, suddenly we are getting this without doing any changes from our side. I noticed this repo updated a few hours ago. must be something that affects it.

Must provide --username with --password-stdin
Error: Process completed with exit code 1.

---------

   - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ steps.ecr.outputs.username }}
        DOCKER_PASSWORD: ${{ steps.ecr.outputs.password }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}"  --password-stdin xxxxxxxx.amazonaws.com

**Comment by elgohr** [comment]
Hi, could you please provide the whole workflow? Which version of the action are you using?

**Comment by elgohr** [comment]
Can reproduce your issue https://github.com/elgohr/ecr-login-action/runs/6142073776?check_suite_focus=true

**Comment by elgohr** [comment]
@sameeraksc should be fixed. Could you please verify?

**Comment by sameeraksc** [comment]
Hey, @elgohr it's working now. thanks.
