### ISSUE TITLE
The set-output command is deprecated

### ISSUE THREAD

**Issue by hendricksond** [elgohr/ecr-login-action#21]
When using this action, this warning appears in the logs:

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

This is generated by the use of `set-output` on lines 19-23 of entrypoint.sh: https://github.com/elgohr/ecr-login-action/blob/c2c29ff786f94a15ca33617fda060e2c44d6b5c9/entrypoint.sh#L19-L23

**Comment by elgohr** [comment]
Hey, thank you for bringing this up

**Comment by hendricksond** [comment]
And thank you for the quick fix!

**Comment by elgohr** [comment]
Was released already https://github.com/elgohr/ecr-login-action/actions/runs/3422438253/jobs/5699857542
Keeping the old syntax for compatibility

**Comment by elgohr** [comment]
https://github.com/elgohr/ecr-login-action/blob/main/.github/workflows/release.yml#L54 is overwriting the tag.

**Comment by elgohr** [comment]
https://github.com/elgohr/ecr-login-action/blob/main/.github/workflows/release.yml#L54 is overwriting the tag.

**Comment by elgohr** [comment]
Will not break peoples workflows due to auto-update to a non-backward compatible version because of somebodies warning list, sorry.

**Comment by hendricksond** [comment]
I don't understand why backwards compatibility is even a concern. Does GitHub allow repos to use outdated action runners?

**Comment by elgohr** [comment]
Until 31st May 2023 this is totally possible (https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by elgohr** [comment]
I guess it would be a compromise to start off fresh in the new year. So people had 2 month for updating self hosted runners

**Comment by elgohr** [comment]
Again, there’s auto update and I’m not going to break peoples workflows.

**Comment by hendricksond** [comment]
It won't break workflows for people who are properly configured using `elgohr/ecr-login-action@v2`. Releasing as a `v3` tag would allow people to opt in to the new behavior using `elgohr/ecr-login-action@v3`. Anyone who doesn't use a version tag already probably doesn't care about breaking changes.

**Comment by elgohr** [comment]
Let's give it a try
